<?php
/**
 * Generated by Haxe 4.3.1
 */

use \php\Boot;
use \haxe\io\Output;
use \sys\io\FileOutput;
use \php\_Boot\HxString;
use \haxe\SysTools;

/**
 * This class provides access to various base functions of system platforms.
 * Look in the `sys` package for more system APIs.
 */
class Sys {
	/**
	 * Returns all the arguments that were passed in the command line.
	 * This does not include the interpreter or the name of the program file.
	 * (java)(eval) On Windows, non-ASCII Unicode arguments will not work correctly.
	 * (cs) Non-ASCII Unicode arguments will not work correctly.
	 * 
	 * @return string[]|\Array_hx
	 */
	public static function args () {
		#D:\tools\haxe\std/php/_std/Sys.hx:78: lines 78-82
		if (array_key_exists("argv", $_SERVER)) {
			#D:\tools\haxe\std/php/_std/Sys.hx:79: characters 4-89
			return \Array_hx::wrap(array_slice($_SERVER["argv"], 1));
		} else {
			#D:\tools\haxe\std/php/_std/Sys.hx:81: characters 4-13
			return new \Array_hx();
		}
	}

	/**
	 * Runs the given command. The command output will be printed to the same output as the current process.
	 * The current process will block until the command terminates.
	 * The return value is the exit code of the command (usually `0` indicates no error).
	 * Command arguments can be passed in two ways:
	 * 1. Using `args` to pass command arguments. Each argument will be automatically quoted and shell meta-characters will be escaped if needed.
	 * `cmd` should be an executable name that can be located in the `PATH` environment variable, or a full path to an executable.
	 * 2. When `args` is not given or is `null`, command arguments can be appended to `cmd`. No automatic quoting/escaping will be performed. `cmd` should be formatted exactly as it would be when typed at the command line.
	 * It can run executables, as well as shell commands that are not executables (e.g. on Windows: `dir`, `cd`, `echo` etc).
	 * Use the `sys.io.Process` API for more complex tasks, such as background processes, or providing input to the command.
	 * 
	 * @param string $cmd
	 * @param string[]|\Array_hx $args
	 * 
	 * @return int
	 */
	public static function command ($cmd, $args = null) {
		#D:\tools\haxe\std/php/_std/Sys.hx:127: lines 127-137
		if ($args !== null) {
			#D:\tools\haxe\std/php/_std/Sys.hx:128: characters 12-24
			if (Sys::systemName() === "Windows") {
				#D:\tools\haxe\std/php/_std/Sys.hx:130: lines 130-133
				$_g = new \Array_hx();
				#D:\tools\haxe\std/php/_std/Sys.hx:131: lines 131-132
				$_g1 = 0;
				$_g2 = (\Array_hx::wrap([\StringTools::replace($cmd, "/", "\\")]))->concat($args);
				while ($_g1 < $_g2->length) {
					#D:\tools\haxe\std/php/_std/Sys.hx:131: characters 12-13
					$a = ($_g2->arr[$_g1] ?? null);
					#D:\tools\haxe\std/php/_std/Sys.hx:131: lines 131-132
					++$_g1;
					#D:\tools\haxe\std/php/_std/Sys.hx:132: characters 8-37
					$x = SysTools::quoteWinArg($a, true);
					$_g->arr[$_g->length++] = $x;
				}
				#D:\tools\haxe\std/php/_std/Sys.hx:130: characters 6-9
				$cmd = $_g->join(" ");
			} else {
				#D:\tools\haxe\std/php/_std/Sys.hx:135: characters 12-57
				$_this = (\Array_hx::wrap([$cmd]))->concat($args);
				$f = Boot::getStaticClosure(SysTools::class, 'quoteUnixArg');
				$result = [];
				$data = $_this->arr;
				$_g_current = 0;
				$_g_length = count($data);
				$_g_data = $data;
				while ($_g_current < $_g_length) {
					$item = $_g_data[$_g_current++];
					$result[] = $f($item);
				}
				#D:\tools\haxe\std/php/_std/Sys.hx:135: characters 6-9
				$cmd = \Array_hx::wrap($result)->join(" ");
			}
		}
		#D:\tools\haxe\std/php/_std/Sys.hx:138: characters 3-30
		$result = Boot::deref(0);
		#D:\tools\haxe\std/php/_std/Sys.hx:139: characters 3-29
		system($cmd, $result);
		#D:\tools\haxe\std/php/_std/Sys.hx:140: characters 3-16
		return $result;
	}

	/**
	 * Returns the value of the given environment variable, or `null` if it
	 * doesn't exist.
	 * 
	 * @param string $s
	 * 
	 * @return string
	 */
	public static function getEnv ($s) {
		#D:\tools\haxe\std/php/_std/Sys.hx:86: characters 3-32
		$value = getenv($s);
		#D:\tools\haxe\std/php/_std/Sys.hx:87: characters 10-39
		if ($value === false) {
			#D:\tools\haxe\std/php/_std/Sys.hx:87: characters 27-31
			return null;
		} else {
			#D:\tools\haxe\std/php/_std/Sys.hx:87: characters 34-39
			return $value;
		}
	}

	/**
	 * Returns the standard error of the process, to which program errors can be written.
	 * 
	 * @return Output
	 */
	public static function stderr () {
		#D:\tools\haxe\std/php/_std/Sys.hx:186: characters 3-87
		$p = (defined("STDERR") ? STDERR : fopen("php://stderr", "w"));
		#D:\tools\haxe\std/php/_std/Sys.hx:187: characters 3-43
		return new FileOutput($p);
	}

	/**
	 * Returns the standard output of the process, to which program output can be written.
	 * 
	 * @return Output
	 */
	public static function stdout () {
		#D:\tools\haxe\std/php/_std/Sys.hx:181: characters 3-87
		$p = (defined("STDOUT") ? STDOUT : fopen("php://stdout", "w"));
		#D:\tools\haxe\std/php/_std/Sys.hx:182: characters 3-43
		return new FileOutput($p);
	}

	/**
	 * Returns the type of the current system. Possible values are:
	 * - `"Windows"`
	 * - `"Linux"`
	 * - `"BSD"`
	 * - `"Mac"`
	 * 
	 * @return string
	 */
	public static function systemName () {
		#D:\tools\haxe\std/php/_std/Sys.hx:121: characters 3-33
		$s = php_uname("s");
		#D:\tools\haxe\std/php/_std/Sys.hx:122: characters 3-26
		$p = HxString::indexOf($s, " ");
		#D:\tools\haxe\std/php/_std/Sys.hx:123: characters 10-39
		if ($p >= 0) {
			#D:\tools\haxe\std/php/_std/Sys.hx:123: characters 20-34
			return mb_substr($s, 0, $p);
		} else {
			#D:\tools\haxe\std/php/_std/Sys.hx:123: characters 37-38
			return $s;
		}
	}
}

Boot::registerClass(Sys::class, 'Sys');
